all:
  vars:
    ansible_user: vagrant
    ansible_host: 127.0.0.1
    ansible_become: yes
    internal_ipv4: "{{ ansible_enp0s8.ipv4.address }}"
  hosts:
    control:
      ansible_ssh_private_key_file: "./.vagrant/machines/control/virtualbox/private_key"
      ansible_port: 60200 
    node-01:
      ansible_ssh_private_key_file: "./.vagrant/machines/node-01/virtualbox/private_key"
      ansible_port: 60201
    node-02:
      ansible_ssh_private_key_file: "./.vagrant/machines/node-02/virtualbox/private_key"
      ansible_port: 60202

  children:
    workers:
      hosts:
       node-01:
       node-02:

