---
- hosts: all
  roles:
    - role: k8s-prep
      tags: prep

    - role: k8s-install
      tags: install


- hosts: control
  roles:
    - role: k8s-init
      tags: init

    - role: k8s-network
      tags: network


- hosts: workers
  roles:
    - role: k8s-worker
      tags: worker

    
