---
- name: create containerd.conf
  copy:
    src: etc_modules-load.d_containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: insert containerd modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: create kubernetes-cri sysctl
  copy:
    src: etc_sysctl.d_99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: reload sysctl
  shell: sysctl --system

