- name: pull k8s images
  shell: kubeadm config images pull
  register: pull
  tags: pull

- debug:
    var: pull
  tags: pull

- name: initialise kubernetes cluster
  shell: "kubeadm init --apiserver-advertise-address {{ internal_ipv4 }} --pod-network-cidr {{ pod_cidr }}"
  register: init
  tags: init

- debug:
    var: init
  tags: init

- name: setup vagrant user for kube config | directory
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: '0700'
    owner: vagrant
    group: vagrant
  tags: kconfig

- name: setup vagrant user for kube config | copy admin conf
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    mode: '0600'
    owner: vagrant
    group: vagrant
  tags: kconfig

