- name: apply calico networking
  become_user: vagrant
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  register: c
  tags: calico
- debug:
    var: c
  tags: calico

- name: check for all pods running
  become_user: vagrant
  shell: kubectl get pods -n kube-system | grep -v NAME | grep -v Running
  register: run
  failed_when: run.rc != 1
  until: run.rc == 1
  retries: 10
  delay: 10
  tags: run


